baseURL = "/"
locale = "en"
defaultContentLanguage = "en"

title = "Hi, I'm Iain Galloway"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "I build software and make music."
  keywords = ["Iain Galloway", "software engineer", "musician"]
  robots = "index, follow"

[mediaTypes."text/netlify-headers"]
  suffixes = [""]

[outputFormats.headers]
  baseName = "_headers"
  isPlainText = true
  mediaType = "text/netlify-headers"
  notAlternative = true
  root = true

[outputs]
  home = ["html", "headers"]
