# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: iaingalloway/iaingalloway-com
  branch: main
  site_domain: iaingalloway.com
  squash_merges: true
publish_mode: editorial_workflow
site_url: https://iaingalloway.com
media_folder: site/assets/images
collections: []
